import localFont from "next/font/local";
import { Raleway } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/page";
import Footer from "./footer/page";
import About from "./about/page";
import Project from "./project/page";
import Contact from "./contact/page";

// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });
const raleway = Raleway({
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Min Khant Kyaw | Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${raleway.className} antialiased relative`}>
				<NavBar />
				<main className="mx-auto flex flex-col gap-10 px-4 sm:px-10">
					{children}
					<About />
					<Project />
					<Contact />
				</main>
				<Footer />
			</body>
		</html>
	);
}
